### ISSUE TITLE
bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by jason-riddle** [nanobox-io/nanobox-engine-python#16]
Getting the following error message when trying to run <code>pip</code>.

``` bash
bash: /code/env/bin/pip: /opt/code/env/bin/python2.7: bad interpreter: No such file or directory
```

My Boxfile looks like the following

``` yaml
env:
  ENVIRONMENT: dev

build:
  engine: python
  python_runtime: python27
  nodejs_runtime: nodejs-4.2
```

I took a look in <code>/code/env/bin/pip</code> and it looks like this

``` bash
#!/opt/code/env/bin/python2.7
```

should be this?

``` bash
#!/code/env/bin/python2.7
```
